# fly.toml app configuration file generated for crosspost-bot on 2025-01-11T15:15:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crosspost-bot'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3000'

[[mounts]]
  source = 'data'
  destination = '/.data'
  initial_size = '1GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
